insert into exercises (id, name, muscle_group) values
(1, 'Barbell Bench Press', 'Pecho'),
(2, 'Incline Bench Press', 'Pecho'),
(3, 'Decline Bench Press', 'Pecho'),
(4, 'Dumbbell Press', 'Pecho'),
(5, 'Incline Dumbbell Press', 'Pecho'),
(6, 'Peck Deck', 'Pecho'),
(7, 'Cable Crossover', 'Pecho'),
(8, 'Chest Dips', 'Pecho'),
(9, 'Dumbbell Pullover', 'Pecho'),
(10, 'Deadlift', 'Espalda'),
(11, 'Wide Grip Pull-ups', 'Espalda'),
(12, 'Neutral Grip Pull-ups', 'Espalda'),
(13, 'Wide Grip Lat Pulldown', 'Espalda'),
(14, 'Close Grip Lat Pulldown', 'Espalda'),
(15, 'Barbell Row', 'Espalda'),
(16, 'Dumbbell Row', 'Espalda'),
(17, 'T-Bar Row', 'Espalda'),
(18, 'Seated Cable Row', 'Espalda'),
(19, 'Cable Pullover', 'Espalda'),
(20, 'Hyperextensions', 'Espalda'),
(21, 'Smith Machine Shoulder Press', 'Hombros'),
(22, 'Dumbbell Overhead Press', 'Hombros'),
(23, 'Arnold Press', 'Hombros'),
(24, 'Lateral Raises', 'Hombros'),
(25, 'Cable Lateral Raises', 'Hombros'),
(26, 'Front Raises', 'Hombros'),
(27, 'Rear Delt Flyes', 'Hombros'),
(28, 'Face Pull', 'Espalda'),
(29, 'Upright Row', 'Hombros'),
(30, 'Dumbbell Shrugs', 'Hombros'),
(31, 'Straight Bar Curl', 'Brazos'),
(32, 'EZ Bar Curl', 'Brazos'),
(33, 'Dumbbell Curl', 'Brazos'),
(34, 'Hammer Curl', 'Brazos'),
(35, 'Concentration Curl', 'Brazos'),
(36, 'Preacher Curl', 'Brazos'),
(37, 'Cable Curl', 'Brazos'),
(38, 'Spider Curl', 'Brazos'),
(39, 'EZ Bar Skull Crusher', 'Brazos'),
(40, 'Dumbbell Skull Crusher', 'Brazos'),
(41, 'Tricep Pushdown (Bar)', 'Brazos'),
(42, 'Tricep Pushdown (Rope)', 'Brazos'),
(43, 'Close Grip Bench Press', 'Brazos'),
(44, 'Bench Dips', 'Brazos'),
(45, 'Tricep Kickback', 'Brazos'),
(46, 'Overhead Tricep Extension', 'Brazos'),
(47, 'Barbell Squat', 'Piernas'),
(48, 'Front Squat', 'Piernas'),
(49, 'Bulgarian Split Squat', 'Piernas'),
(50, 'Leg Press', 'Piernas'),
(51, 'Leg Extension', 'Piernas'),
(52, 'Barbell Lunges', 'Piernas'),
(53, 'Dumbbell Lunges', 'Piernas'),
(54, 'Hack Squat', 'Piernas'),
(55, 'Lying Leg Curl', 'Piernas'),
(56, 'Seated Leg Curl', 'Piernas'),
(57, 'Romanian Deadlift', 'Piernas'),
(58, 'Good Mornings', 'Piernas'),
(59, 'Stiff-Leg Deadlift', 'Piernas'),
(60, 'Barbell Hip Thrust', 'Glúteos'),
(61, 'Dumbbell Hip Thrust', 'Glúteos'),
(62, 'Cable Glute Kickback', 'Glúteos'),
(63, 'Machine Hip Abduction', 'Glúteos'),
(64, 'Sumo Squat', 'Glúteos'),
(65, 'Glute Bridge', 'Glúteos'),
(66, 'Standing Calf Raises', 'Piernas'),
(67, 'Seated Calf Raises', 'Piernas'),
(68, 'Leg Press Calf Raises', 'Piernas'),
(69, 'Donkey Calf Raises', 'Piernas'),
(70, 'Plank', 'Core'),
(71, 'Side Plank', 'Core'),
(72, 'Crunch', 'Core'),
(73, 'Reverse Crunch', 'Core'),
(74, 'Ab Wheel Rollout', 'Core'),
(75, 'Hanging Leg Raises', 'Core'),
(76, 'Russian Twist', 'Core'),
(77, 'Cable Crunch', 'Core'),
(78, 'Dragon Flag', 'Core')
;

-- Resetear la secuencia para que los nuevos ejercicios no colisionen con los seed
select setval('exercises_id_seq', (select max(id) from exercises));
